# Generated by Django 4.1.4 on 2023-01-06 16:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=200, null=True)),
                ('prenom', models.CharField(max_length=200, null=True)),
                ('messagerie_electronique', models.CharField(max_length=200, null=True)),
                ('num', models.IntegerField()),
                ('adresse', models.IntegerField()),
                ('ville', models.CharField(max_length=200, null=True)),
                ('pays', models.CharField(max_length=200, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='TailleVehicule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=200, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='TypeVehicule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=200, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Vehicule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.CharField(max_length=200, null=True)),
                ('cout', models.IntegerField()),
                ('taille', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mini_projets.taillevehicule')),
                ('type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mini_projets.typevehicule')),
            ],
        ),
        migrations.CreateModel(
            name='TarifLocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tarif', models.CharField(max_length=200, null=True)),
                ('taille_vehicule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mini_projets.taillevehicule')),
                ('type_vehicule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mini_projets.typevehicule')),
            ],
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location_date', models.CharField(max_length=200, null=True)),
                ('return_date', models.CharField(max_length=200, null=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mini_projets.client')),
                ('vehicule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mini_projets.vehicule')),
            ],
        ),
    ]
